chore(tools): add totals to renovate-audit

diff --git a/_tools/renovate-audit b/_tools/renovate-audit
--- a/_tools/renovate-audit
+++ b/_tools/renovate-audit
@@ -19,6 +19,9 @@ gh pr list \
   sort -u >"$tmp"
 
 ret=0
+updated=0
+waiting=0
+missing=0
 
 for info in */info.yaml; do
   dep=$(dirname "$info")
@@ -31,6 +34,7 @@ for info in */info.yaml; do
   fi
 
   if grep -Fxq "$dep" "$tmp"; then
+    ((updated++)) || true
     printf ' \e[32m✓\e[0m \e[35m%s\e[0m is updated by renovate\n' "$dep"
     continue
   fi
@@ -45,17 +49,22 @@ for info in */info.yaml; do
     -name package.json \
     \) \
     -exec false {} +; then
+    ((waiting++)) || true
     printf ' \e[1;33m⏲\e[0m \e[35m%s\e[0m is configured, but not yet updated by renovate\n' "$dep"
     continue
   fi
 
   if jq -r '.customManagers[] | .fileMatch[]' renovate.json | grep -q "^$dep/.*"; then
+    ((waiting++)) || true
     printf ' \e[1;33m⏲\e[0m \e[35m%s\e[0m is configured, but not yet updated by renovate\n' "$dep"
     continue
   fi
 
   printf ' \e[31m✗\e[0m \e[35m%s\e[0m is \e[1mnot\e[0m renovate-maintained\n' "$dep" >&2
+  ((missing++)) || true
   ret=1
 done
 
+echo
+printf 'Updated: \e[32m%d\e[0m, waiting: \e[33m%d\e[0m, missing: \e[31m%d\e[0m\n' "$updated" "$waiting" "$missing"
 exit "$ret"
