WIP: CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,9 +32,8 @@ matrix:
     - env: RESTYLER=yapf
 install: gem install rspec
 script: |
-  # empty $mb means we're on master. we'll just try against parent
-  mb=$(git merge-base master HEAD)
-  mb=${mb:-HEAD^}
+  # failure means we're on the "push" job. we'll just diff against parent
+  mb=$(git merge-base master HEAD 2>/dev/null || echo "HEAD^")
 
   if ! git diff --name-only "$mb" | grep -q "^${RESTYLER}/"; then
     echo "$RESTYLER unchanged, skipping."
