*refactors wildly*

diff --git a/build/ci b/build/ci
--- a/build/ci
+++ b/build/ci
@@ -1,28 +1,20 @@
 #!/usr/bin/env bash
 set -eu
 
-# failure means we're on the "push" job. we'll just diff against parent
-mb=$(git merge-base master HEAD 2>/dev/null || echo "HEAD^")
+# TEMPORARY, build all the things!
+# # failure means we're on the "push" job. we'll just diff against parent
+# mb=$(git merge-base master HEAD 2>/dev/null || echo "HEAD^")
 
-if ! git diff --name-only "$mb" | grep -q "^restylers/${RESTYLER}/"; then
-  echo "$RESTYLER unchanged, skipping."
-  exit 0
-fi
-
-docker run --rm \
-  --volume /var/run/docker.sock:/var/run/docker.sock \
-  --volume /tmp:/tmp \
-  --volume "$PWD":/code:ro \
-  restyled/restylers:v1 \
-  restylers build "restylers/$RESTYLER/info.yaml"
-
-docker run --rm \
-  --volume /var/run/docker.sock:/var/run/docker.sock \
-  --volume /tmp:/tmp \
-  --volume "$PWD":/code:ro \
-  restyled/restylers:v1 \
-  restylers test "restylers/$RESTYLER/info.yaml"
+# if ! git diff --name-only "$mb" | grep -q "^restylers/${RESTYLER}/"; then
+#   echo "$RESTYLER unchanged, skipping."
+#   exit 0
+# fi
 
 if [ -f "restylers/$RESTYLER/Dockerfile" ]; then
+  # TODO: ./build/restylers lint
   ./build/hadolint-pretty "restylers/$RESTYLER/Dockerfile"
 fi
+
+./build/restylers build "restylers/$RESTYLER/info.yaml"
+./build/restylers test "restylers/$RESTYLER/info.yaml"
+./build/restylers check "restylers/$RESTYLER/info.yaml"
